//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.3053
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServer_Lib
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WcfDataServer_Lib")]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool BoolValueField;
        
        private string StringValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue
        {
            get
            {
                return this.BoolValueField;
            }
            set
            {
                this.BoolValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue
        {
            get
            {
                return this.StringValueField;
            }
            set
            {
                this.StringValueField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IWcfDataServer")]
public interface IWcfDataServer
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfDataServer/GetData", ReplyAction="http://tempuri.org/IWcfDataServer/GetDataResponse")]
    string GetData(int value);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWcfDataServer/GetData", ReplyAction="http://tempuri.org/IWcfDataServer/GetDataResponse")]
    System.IAsyncResult BeginGetData(int value, System.AsyncCallback callback, object asyncState);
    
    string EndGetData(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfDataServer/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IWcfDataServer/GetDataUsingDataContractResponse")]
    WcfDataServer_Lib.CompositeType GetDataUsingDataContract(WcfDataServer_Lib.CompositeType composite);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWcfDataServer/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IWcfDataServer/GetDataUsingDataContractResponse")]
    System.IAsyncResult BeginGetDataUsingDataContract(WcfDataServer_Lib.CompositeType composite, System.AsyncCallback callback, object asyncState);
    
    WcfDataServer_Lib.CompositeType EndGetDataUsingDataContract(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfDataServer/GetDSValueAsByteBuffer", ReplyAction="http://tempuri.org/IWcfDataServer/GetDSValueAsByteBufferResponse")]
    System.IO.MemoryStream GetDSValueAsByteBuffer(byte[] arr);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWcfDataServer/GetDSValueAsByteBuffer", ReplyAction="http://tempuri.org/IWcfDataServer/GetDSValueAsByteBufferResponse")]
    System.IAsyncResult BeginGetDSValueAsByteBuffer(byte[] arr, System.AsyncCallback callback, object asyncState);
    
    System.IO.MemoryStream EndGetDSValueAsByteBuffer(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfDataServer/RunCMD", ReplyAction="http://tempuri.org/IWcfDataServer/RunCMDResponse")]
    void RunCMD(byte numksdu, ushort numvtu, int tagguid, byte[] arr);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWcfDataServer/RunCMD", ReplyAction="http://tempuri.org/IWcfDataServer/RunCMDResponse")]
    System.IAsyncResult BeginRunCMD(byte numksdu, ushort numvtu, int tagguid, byte[] arr, System.AsyncCallback callback, object asyncState);
    
    void EndRunCMD(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfDataServer/GetDSGUIDs", ReplyAction="http://tempuri.org/IWcfDataServer/GetDSGUIDsResponse")]
    string GetDSGUIDs();
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWcfDataServer/GetDSGUIDs", ReplyAction="http://tempuri.org/IWcfDataServer/GetDSGUIDsResponse")]
    System.IAsyncResult BeginGetDSGUIDs(System.AsyncCallback callback, object asyncState);
    
    string EndGetDSGUIDs(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfDataServer/GetDSINFO", ReplyAction="http://tempuri.org/IWcfDataServer/GetDSINFOResponse")]
    string GetDSINFO(string DSGuid);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWcfDataServer/GetDSINFO", ReplyAction="http://tempuri.org/IWcfDataServer/GetDSINFOResponse")]
    System.IAsyncResult BeginGetDSINFO(string DSGuid, System.AsyncCallback callback, object asyncState);
    
    string EndGetDSINFO(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfDataServer/GetSourceGUIDs", ReplyAction="http://tempuri.org/IWcfDataServer/GetSourceGUIDsResponse")]
    string GetSourceGUIDs(string DSGuid);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWcfDataServer/GetSourceGUIDs", ReplyAction="http://tempuri.org/IWcfDataServer/GetSourceGUIDsResponse")]
    System.IAsyncResult BeginGetSourceGUIDs(string DSGuid, System.AsyncCallback callback, object asyncState);
    
    string EndGetSourceGUIDs(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfDataServer/GetSourceName", ReplyAction="http://tempuri.org/IWcfDataServer/GetSourceNameResponse")]
    string GetSourceName(string DSGuid, string SrcGuid);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWcfDataServer/GetSourceName", ReplyAction="http://tempuri.org/IWcfDataServer/GetSourceNameResponse")]
    System.IAsyncResult BeginGetSourceName(string DSGuid, string SrcGuid, System.AsyncCallback callback, object asyncState);
    
    string EndGetSourceName(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfDataServer/GetECUGUIDs", ReplyAction="http://tempuri.org/IWcfDataServer/GetECUGUIDsResponse")]
    string GetECUGUIDs(string DSGuid, string SrcGuid);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWcfDataServer/GetECUGUIDs", ReplyAction="http://tempuri.org/IWcfDataServer/GetECUGUIDsResponse")]
    System.IAsyncResult BeginGetECUGUIDs(string DSGuid, string SrcGuid, System.AsyncCallback callback, object asyncState);
    
    string EndGetECUGUIDs(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfDataServer/GetECUName", ReplyAction="http://tempuri.org/IWcfDataServer/GetECUNameResponse")]
    string GetECUName(string DSGuid, string SrcGuid, string EcuGuid);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWcfDataServer/GetECUName", ReplyAction="http://tempuri.org/IWcfDataServer/GetECUNameResponse")]
    System.IAsyncResult BeginGetECUName(string DSGuid, string SrcGuid, string EcuGuid, System.AsyncCallback callback, object asyncState);
    
    string EndGetECUName(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfDataServer/GetRTUGUIDs", ReplyAction="http://tempuri.org/IWcfDataServer/GetRTUGUIDsResponse")]
    string GetRTUGUIDs(string DSGuid, string SrcGuid, string EcuGuid);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWcfDataServer/GetRTUGUIDs", ReplyAction="http://tempuri.org/IWcfDataServer/GetRTUGUIDsResponse")]
    System.IAsyncResult BeginGetRTUGUIDs(string DSGuid, string SrcGuid, string EcuGuid, System.AsyncCallback callback, object asyncState);
    
    string EndGetRTUGUIDs(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfDataServer/GetRTUTypeName", ReplyAction="http://tempuri.org/IWcfDataServer/GetRTUTypeNameResponse")]
    string GetRTUTypeName(string DSGuid, string SrcGuid, string EcuGuid, string RtuGuid);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWcfDataServer/GetRTUTypeName", ReplyAction="http://tempuri.org/IWcfDataServer/GetRTUTypeNameResponse")]
    System.IAsyncResult BeginGetRTUTypeName(string DSGuid, string SrcGuid, string EcuGuid, string RtuGuid, System.AsyncCallback callback, object asyncState);
    
    string EndGetRTUTypeName(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfDataServer/GetRTUDescription", ReplyAction="http://tempuri.org/IWcfDataServer/GetRTUDescriptionResponse")]
    string GetRTUDescription(string DSGuid, string SrcGuid, string EcuGuid, string RtuGuid);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWcfDataServer/GetRTUDescription", ReplyAction="http://tempuri.org/IWcfDataServer/GetRTUDescriptionResponse")]
    System.IAsyncResult BeginGetRTUDescription(string DSGuid, string SrcGuid, string EcuGuid, string RtuGuid, System.AsyncCallback callback, object asyncState);
    
    string EndGetRTUDescription(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfDataServer/IsRTUEnable", ReplyAction="http://tempuri.org/IWcfDataServer/IsRTUEnableResponse")]
    bool IsRTUEnable(string DSGuid, string SrcGuid, string EcuGuid, string RtuGuid);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWcfDataServer/IsRTUEnable", ReplyAction="http://tempuri.org/IWcfDataServer/IsRTUEnableResponse")]
    System.IAsyncResult BeginIsRTUEnable(string DSGuid, string SrcGuid, string EcuGuid, string RtuGuid, System.AsyncCallback callback, object asyncState);
    
    bool EndIsRTUEnable(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfDataServer/GetGroupGUIDs", ReplyAction="http://tempuri.org/IWcfDataServer/GetGroupGUIDsResponse")]
    string GetGroupGUIDs(string DSGuid, string SrcGuid, string EcuGuid, string RtuGuid);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWcfDataServer/GetGroupGUIDs", ReplyAction="http://tempuri.org/IWcfDataServer/GetGroupGUIDsResponse")]
    System.IAsyncResult BeginGetGroupGUIDs(string DSGuid, string SrcGuid, string EcuGuid, string RtuGuid, System.AsyncCallback callback, object asyncState);
    
    string EndGetGroupGUIDs(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfDataServer/GetSubGroupGUIDsInGroup", ReplyAction="http://tempuri.org/IWcfDataServer/GetSubGroupGUIDsInGroupResponse")]
    string GetSubGroupGUIDsInGroup(string DSGuid, string SrcGuid, string EcuGuid, string RtuGuid, string GroupGuid);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWcfDataServer/GetSubGroupGUIDsInGroup", ReplyAction="http://tempuri.org/IWcfDataServer/GetSubGroupGUIDsInGroupResponse")]
    System.IAsyncResult BeginGetSubGroupGUIDsInGroup(string DSGuid, string SrcGuid, string EcuGuid, string RtuGuid, string GroupGuid, System.AsyncCallback callback, object asyncState);
    
    string EndGetSubGroupGUIDsInGroup(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfDataServer/GetRTUGroupName", ReplyAction="http://tempuri.org/IWcfDataServer/GetRTUGroupNameResponse")]
    string GetRTUGroupName(string DSGuid, string SrcGuid, string EcuGuid, string RtuGuid, string GroupGuid);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWcfDataServer/GetRTUGroupName", ReplyAction="http://tempuri.org/IWcfDataServer/GetRTUGroupNameResponse")]
    System.IAsyncResult BeginGetRTUGroupName(string DSGuid, string SrcGuid, string EcuGuid, string RtuGuid, string GroupGuid, System.AsyncCallback callback, object asyncState);
    
    string EndGetRTUGroupName(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfDataServer/IsGroupEnable", ReplyAction="http://tempuri.org/IWcfDataServer/IsGroupEnableResponse")]
    bool IsGroupEnable(string DSGuid, string SrcGuid, string EcuGuid, string RtuGuid, string GroupGuid);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWcfDataServer/IsGroupEnable", ReplyAction="http://tempuri.org/IWcfDataServer/IsGroupEnableResponse")]
    System.IAsyncResult BeginIsGroupEnable(string DSGuid, string SrcGuid, string EcuGuid, string RtuGuid, string GroupGuid, System.AsyncCallback callback, object asyncState);
    
    bool EndIsGroupEnable(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfDataServer/GetRtuTagGUIDs", ReplyAction="http://tempuri.org/IWcfDataServer/GetRtuTagGUIDsResponse")]
    string GetRtuTagGUIDs(string DSGuid, string SrcGuid, string EcuGuid, string RtuGuid);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWcfDataServer/GetRtuTagGUIDs", ReplyAction="http://tempuri.org/IWcfDataServer/GetRtuTagGUIDsResponse")]
    System.IAsyncResult BeginGetRtuTagGUIDs(string DSGuid, string SrcGuid, string EcuGuid, string RtuGuid, System.AsyncCallback callback, object asyncState);
    
    string EndGetRtuTagGUIDs(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfDataServer/GetRtuGroupTagGUIDs", ReplyAction="http://tempuri.org/IWcfDataServer/GetRtuGroupTagGUIDsResponse")]
    string GetRtuGroupTagGUIDs(string DSGuid, string SrcGuid, string EcuGuid, string RtuGuid, string GroupGuid);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWcfDataServer/GetRtuGroupTagGUIDs", ReplyAction="http://tempuri.org/IWcfDataServer/GetRtuGroupTagGUIDsResponse")]
    System.IAsyncResult BeginGetRtuGroupTagGUIDs(string DSGuid, string SrcGuid, string EcuGuid, string RtuGuid, string GroupGuid, System.AsyncCallback callback, object asyncState);
    
    string EndGetRtuGroupTagGUIDs(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfDataServer/GetRTUTagName", ReplyAction="http://tempuri.org/IWcfDataServer/GetRTUTagNameResponse")]
    string GetRTUTagName(string DSGuid, string SrcGuid, string EcuGuid, string RtuGuid, string GroupGuid, string TagGUID);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWcfDataServer/GetRTUTagName", ReplyAction="http://tempuri.org/IWcfDataServer/GetRTUTagNameResponse")]
    System.IAsyncResult BeginGetRTUTagName(string DSGuid, string SrcGuid, string EcuGuid, string RtuGuid, string GroupGuid, string TagGUID, System.AsyncCallback callback, object asyncState);
    
    string EndGetRTUTagName(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfDataServer/GetDSLastErrorGUID", ReplyAction="http://tempuri.org/IWcfDataServer/GetDSLastErrorGUIDResponse")]
    string GetDSLastErrorGUID();
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWcfDataServer/GetDSLastErrorGUID", ReplyAction="http://tempuri.org/IWcfDataServer/GetDSLastErrorGUIDResponse")]
    System.IAsyncResult BeginGetDSLastErrorGUID(System.AsyncCallback callback, object asyncState);
    
    string EndGetDSLastErrorGUID(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfDataServer/GetDSLastErrorTextByErrorGUID", ReplyAction="http://tempuri.org/IWcfDataServer/GetDSLastErrorTextByErrorGUIDResponse")]
    string GetDSLastErrorTextByErrorGUID(string lastErrorGUID);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IWcfDataServer/GetDSLastErrorTextByErrorGUID", ReplyAction="http://tempuri.org/IWcfDataServer/GetDSLastErrorTextByErrorGUIDResponse")]
    System.IAsyncResult BeginGetDSLastErrorTextByErrorGUID(string lastErrorGUID, System.AsyncCallback callback, object asyncState);
    
    string EndGetDSLastErrorTextByErrorGUID(System.IAsyncResult result);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IWcfDataServerChannel : IWcfDataServer, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class WcfDataServerClient : System.ServiceModel.ClientBase<IWcfDataServer>, IWcfDataServer
{
    
    public WcfDataServerClient()
    {
    }
    
    public WcfDataServerClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public WcfDataServerClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public WcfDataServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public WcfDataServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string GetData(int value)
    {
        return base.Channel.GetData(value);
    }
    
    public System.IAsyncResult BeginGetData(int value, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetData(value, callback, asyncState);
    }
    
    public string EndGetData(System.IAsyncResult result)
    {
        return base.Channel.EndGetData(result);
    }
    
    public WcfDataServer_Lib.CompositeType GetDataUsingDataContract(WcfDataServer_Lib.CompositeType composite)
    {
        return base.Channel.GetDataUsingDataContract(composite);
    }
    
    public System.IAsyncResult BeginGetDataUsingDataContract(WcfDataServer_Lib.CompositeType composite, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetDataUsingDataContract(composite, callback, asyncState);
    }
    
    public WcfDataServer_Lib.CompositeType EndGetDataUsingDataContract(System.IAsyncResult result)
    {
        return base.Channel.EndGetDataUsingDataContract(result);
    }
    
    public System.IO.MemoryStream GetDSValueAsByteBuffer(byte[] arr)
    {
        return base.Channel.GetDSValueAsByteBuffer(arr);
    }
    
    public System.IAsyncResult BeginGetDSValueAsByteBuffer(byte[] arr, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetDSValueAsByteBuffer(arr, callback, asyncState);
    }
    
    public System.IO.MemoryStream EndGetDSValueAsByteBuffer(System.IAsyncResult result)
    {
        return base.Channel.EndGetDSValueAsByteBuffer(result);
    }
    
    public void RunCMD(byte numksdu, ushort numvtu, int tagguid, byte[] arr)
    {
        base.Channel.RunCMD(numksdu, numvtu, tagguid, arr);
    }
    
    public System.IAsyncResult BeginRunCMD(byte numksdu, ushort numvtu, int tagguid, byte[] arr, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginRunCMD(numksdu, numvtu, tagguid, arr, callback, asyncState);
    }
    
    public void EndRunCMD(System.IAsyncResult result)
    {
        base.Channel.EndRunCMD(result);
    }
    
    public string GetDSGUIDs()
    {
        return base.Channel.GetDSGUIDs();
    }
    
    public System.IAsyncResult BeginGetDSGUIDs(System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetDSGUIDs(callback, asyncState);
    }
    
    public string EndGetDSGUIDs(System.IAsyncResult result)
    {
        return base.Channel.EndGetDSGUIDs(result);
    }
    
    public string GetDSINFO(string DSGuid)
    {
        return base.Channel.GetDSINFO(DSGuid);
    }
    
    public System.IAsyncResult BeginGetDSINFO(string DSGuid, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetDSINFO(DSGuid, callback, asyncState);
    }
    
    public string EndGetDSINFO(System.IAsyncResult result)
    {
        return base.Channel.EndGetDSINFO(result);
    }
    
    public string GetSourceGUIDs(string DSGuid)
    {
        return base.Channel.GetSourceGUIDs(DSGuid);
    }
    
    public System.IAsyncResult BeginGetSourceGUIDs(string DSGuid, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetSourceGUIDs(DSGuid, callback, asyncState);
    }
    
    public string EndGetSourceGUIDs(System.IAsyncResult result)
    {
        return base.Channel.EndGetSourceGUIDs(result);
    }
    
    public string GetSourceName(string DSGuid, string SrcGuid)
    {
        return base.Channel.GetSourceName(DSGuid, SrcGuid);
    }
    
    public System.IAsyncResult BeginGetSourceName(string DSGuid, string SrcGuid, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetSourceName(DSGuid, SrcGuid, callback, asyncState);
    }
    
    public string EndGetSourceName(System.IAsyncResult result)
    {
        return base.Channel.EndGetSourceName(result);
    }
    
    public string GetECUGUIDs(string DSGuid, string SrcGuid)
    {
        return base.Channel.GetECUGUIDs(DSGuid, SrcGuid);
    }
    
    public System.IAsyncResult BeginGetECUGUIDs(string DSGuid, string SrcGuid, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetECUGUIDs(DSGuid, SrcGuid, callback, asyncState);
    }
    
    public string EndGetECUGUIDs(System.IAsyncResult result)
    {
        return base.Channel.EndGetECUGUIDs(result);
    }
    
    public string GetECUName(string DSGuid, string SrcGuid, string EcuGuid)
    {
        return base.Channel.GetECUName(DSGuid, SrcGuid, EcuGuid);
    }
    
    public System.IAsyncResult BeginGetECUName(string DSGuid, string SrcGuid, string EcuGuid, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetECUName(DSGuid, SrcGuid, EcuGuid, callback, asyncState);
    }
    
    public string EndGetECUName(System.IAsyncResult result)
    {
        return base.Channel.EndGetECUName(result);
    }
    
    public string GetRTUGUIDs(string DSGuid, string SrcGuid, string EcuGuid)
    {
        return base.Channel.GetRTUGUIDs(DSGuid, SrcGuid, EcuGuid);
    }
    
    public System.IAsyncResult BeginGetRTUGUIDs(string DSGuid, string SrcGuid, string EcuGuid, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetRTUGUIDs(DSGuid, SrcGuid, EcuGuid, callback, asyncState);
    }
    
    public string EndGetRTUGUIDs(System.IAsyncResult result)
    {
        return base.Channel.EndGetRTUGUIDs(result);
    }
    
    public string GetRTUTypeName(string DSGuid, string SrcGuid, string EcuGuid, string RtuGuid)
    {
        return base.Channel.GetRTUTypeName(DSGuid, SrcGuid, EcuGuid, RtuGuid);
    }
    
    public System.IAsyncResult BeginGetRTUTypeName(string DSGuid, string SrcGuid, string EcuGuid, string RtuGuid, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetRTUTypeName(DSGuid, SrcGuid, EcuGuid, RtuGuid, callback, asyncState);
    }
    
    public string EndGetRTUTypeName(System.IAsyncResult result)
    {
        return base.Channel.EndGetRTUTypeName(result);
    }
    
    public string GetRTUDescription(string DSGuid, string SrcGuid, string EcuGuid, string RtuGuid)
    {
        return base.Channel.GetRTUDescription(DSGuid, SrcGuid, EcuGuid, RtuGuid);
    }
    
    public System.IAsyncResult BeginGetRTUDescription(string DSGuid, string SrcGuid, string EcuGuid, string RtuGuid, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetRTUDescription(DSGuid, SrcGuid, EcuGuid, RtuGuid, callback, asyncState);
    }
    
    public string EndGetRTUDescription(System.IAsyncResult result)
    {
        return base.Channel.EndGetRTUDescription(result);
    }
    
    public bool IsRTUEnable(string DSGuid, string SrcGuid, string EcuGuid, string RtuGuid)
    {
        return base.Channel.IsRTUEnable(DSGuid, SrcGuid, EcuGuid, RtuGuid);
    }
    
    public System.IAsyncResult BeginIsRTUEnable(string DSGuid, string SrcGuid, string EcuGuid, string RtuGuid, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginIsRTUEnable(DSGuid, SrcGuid, EcuGuid, RtuGuid, callback, asyncState);
    }
    
    public bool EndIsRTUEnable(System.IAsyncResult result)
    {
        return base.Channel.EndIsRTUEnable(result);
    }
    
    public string GetGroupGUIDs(string DSGuid, string SrcGuid, string EcuGuid, string RtuGuid)
    {
        return base.Channel.GetGroupGUIDs(DSGuid, SrcGuid, EcuGuid, RtuGuid);
    }
    
    public System.IAsyncResult BeginGetGroupGUIDs(string DSGuid, string SrcGuid, string EcuGuid, string RtuGuid, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetGroupGUIDs(DSGuid, SrcGuid, EcuGuid, RtuGuid, callback, asyncState);
    }
    
    public string EndGetGroupGUIDs(System.IAsyncResult result)
    {
        return base.Channel.EndGetGroupGUIDs(result);
    }
    
    public string GetSubGroupGUIDsInGroup(string DSGuid, string SrcGuid, string EcuGuid, string RtuGuid, string GroupGuid)
    {
        return base.Channel.GetSubGroupGUIDsInGroup(DSGuid, SrcGuid, EcuGuid, RtuGuid, GroupGuid);
    }
    
    public System.IAsyncResult BeginGetSubGroupGUIDsInGroup(string DSGuid, string SrcGuid, string EcuGuid, string RtuGuid, string GroupGuid, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetSubGroupGUIDsInGroup(DSGuid, SrcGuid, EcuGuid, RtuGuid, GroupGuid, callback, asyncState);
    }
    
    public string EndGetSubGroupGUIDsInGroup(System.IAsyncResult result)
    {
        return base.Channel.EndGetSubGroupGUIDsInGroup(result);
    }
    
    public string GetRTUGroupName(string DSGuid, string SrcGuid, string EcuGuid, string RtuGuid, string GroupGuid)
    {
        return base.Channel.GetRTUGroupName(DSGuid, SrcGuid, EcuGuid, RtuGuid, GroupGuid);
    }
    
    public System.IAsyncResult BeginGetRTUGroupName(string DSGuid, string SrcGuid, string EcuGuid, string RtuGuid, string GroupGuid, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetRTUGroupName(DSGuid, SrcGuid, EcuGuid, RtuGuid, GroupGuid, callback, asyncState);
    }
    
    public string EndGetRTUGroupName(System.IAsyncResult result)
    {
        return base.Channel.EndGetRTUGroupName(result);
    }
    
    public bool IsGroupEnable(string DSGuid, string SrcGuid, string EcuGuid, string RtuGuid, string GroupGuid)
    {
        return base.Channel.IsGroupEnable(DSGuid, SrcGuid, EcuGuid, RtuGuid, GroupGuid);
    }
    
    public System.IAsyncResult BeginIsGroupEnable(string DSGuid, string SrcGuid, string EcuGuid, string RtuGuid, string GroupGuid, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginIsGroupEnable(DSGuid, SrcGuid, EcuGuid, RtuGuid, GroupGuid, callback, asyncState);
    }
    
    public bool EndIsGroupEnable(System.IAsyncResult result)
    {
        return base.Channel.EndIsGroupEnable(result);
    }
    
    public string GetRtuTagGUIDs(string DSGuid, string SrcGuid, string EcuGuid, string RtuGuid)
    {
        return base.Channel.GetRtuTagGUIDs(DSGuid, SrcGuid, EcuGuid, RtuGuid);
    }
    
    public System.IAsyncResult BeginGetRtuTagGUIDs(string DSGuid, string SrcGuid, string EcuGuid, string RtuGuid, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetRtuTagGUIDs(DSGuid, SrcGuid, EcuGuid, RtuGuid, callback, asyncState);
    }
    
    public string EndGetRtuTagGUIDs(System.IAsyncResult result)
    {
        return base.Channel.EndGetRtuTagGUIDs(result);
    }
    
    public string GetRtuGroupTagGUIDs(string DSGuid, string SrcGuid, string EcuGuid, string RtuGuid, string GroupGuid)
    {
        return base.Channel.GetRtuGroupTagGUIDs(DSGuid, SrcGuid, EcuGuid, RtuGuid, GroupGuid);
    }
    
    public System.IAsyncResult BeginGetRtuGroupTagGUIDs(string DSGuid, string SrcGuid, string EcuGuid, string RtuGuid, string GroupGuid, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetRtuGroupTagGUIDs(DSGuid, SrcGuid, EcuGuid, RtuGuid, GroupGuid, callback, asyncState);
    }
    
    public string EndGetRtuGroupTagGUIDs(System.IAsyncResult result)
    {
        return base.Channel.EndGetRtuGroupTagGUIDs(result);
    }
    
    public string GetRTUTagName(string DSGuid, string SrcGuid, string EcuGuid, string RtuGuid, string GroupGuid, string TagGUID)
    {
        return base.Channel.GetRTUTagName(DSGuid, SrcGuid, EcuGuid, RtuGuid, GroupGuid, TagGUID);
    }
    
    public System.IAsyncResult BeginGetRTUTagName(string DSGuid, string SrcGuid, string EcuGuid, string RtuGuid, string GroupGuid, string TagGUID, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetRTUTagName(DSGuid, SrcGuid, EcuGuid, RtuGuid, GroupGuid, TagGUID, callback, asyncState);
    }
    
    public string EndGetRTUTagName(System.IAsyncResult result)
    {
        return base.Channel.EndGetRTUTagName(result);
    }
    
    public string GetDSLastErrorGUID()
    {
        return base.Channel.GetDSLastErrorGUID();
    }
    
    public System.IAsyncResult BeginGetDSLastErrorGUID(System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetDSLastErrorGUID(callback, asyncState);
    }
    
    public string EndGetDSLastErrorGUID(System.IAsyncResult result)
    {
        return base.Channel.EndGetDSLastErrorGUID(result);
    }
    
    public string GetDSLastErrorTextByErrorGUID(string lastErrorGUID)
    {
        return base.Channel.GetDSLastErrorTextByErrorGUID(lastErrorGUID);
    }
    
    public System.IAsyncResult BeginGetDSLastErrorTextByErrorGUID(string lastErrorGUID, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginGetDSLastErrorTextByErrorGUID(lastErrorGUID, callback, asyncState);
    }
    
    public string EndGetDSLastErrorTextByErrorGUID(System.IAsyncResult result)
    {
        return base.Channel.EndGetDSLastErrorTextByErrorGUID(result);
    }
}
